version: '3.1'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
      - /app/node_modules/
      - /app/dist/
      - /app/database/
    restart: always
    tty: true
    ports:
      - "17365:17365"
      - "80:80"
      - "81:81"
      - "27017:27017"
      - "20001:20001"
      - "1234:1234"
    depends_on:
      - mongodb
    environment:
      - MONGODB_PORT_27017_TCP_ADDR=mongodb
  mongodb:
    image: mongo:latest
    volumes:
      - ./database:/data/db
    command: mongod --smallfiles --bind_ip=0.0.0.0 --logpath=/dev/null
    expose:
      - 27017

  adminmongo:
    image: mrvautin/adminmongo
    links:
      - mongodb
    tty: true
    ports:
      - "127.0.0.1:1234:1234"
    environment:
      - CONN_NAME=zenbot_mongodb
      - DB_HOST=mongodb
      - DB_PORT=27017
      - HOST=0.0.0.0
    command: "npm start"